"""empty message

Revision ID: 4eacd4098ad3
Revises: 
Create Date: 2016-01-19 14:39:01.513706

"""

# revision identifiers, used by Alembic.
revision = '4eacd4098ad3'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=8192), nullable=False),
    sa.Column('scheme', sa.Binary(), nullable=False),
    sa.Column('netloc', sa.Binary(), nullable=False),
    sa.Column('path', sa.Binary(), nullable=False),
    sa.Column('query', sa.Binary(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=False),
    sa.Column('archive_path', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_full_url', 'url', ['scheme', 'netloc', 'path', 'query'], unique=False)
    op.create_table('url_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=True),
    sa.Column('variant', sa.String(length=32), nullable=False),
    sa.Column('data', postgresql.JSON(), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], [u'url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_variant')
    op.drop_index('ix_full_url', table_name='url')
    op.drop_table('url')
    ### end Alembic commands ###
